spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:db/changelog-master.yml
    liquibase-schema: public
    enabled: true

path:
  to:
    photos:
      folder: src/main/resources/static/
server:
  error:
    include-message: always
    include-binding-errors: always